### PR TITLE
After installing via 'apt-get install webradio.py' I ended up with a …

### PR DESCRIPTION
**Pull request by HiranChaudhuri**
…webradio that looked like fullscreen but was lacking one pixel on top and one to the left. After adding this command line switch this was gone.

### CODE REVIEW

**Comment by HiranChaudhuri** [comment]
Negative. I usually see the wall loading (but that is not a fullscreen picture), then it switched to the image with lines to the left and top. Indeed these lines were the window decoration - with a mouse I was able to drag the window down to see the rest of the decoration and desktop. All this was fixed when I added the command line switch for fullscreen into the systemd startup.

The splash screen is still not fullscreen, and when I tried to look into that I think there was a comment from you that this had not worked for you either.

**Comment by HiranChaudhuri** [comment]
I just restored the default setup, which was to just remove "--fullscreen" from the systemd startup file, then I created these two screenshots for you

windowdecoration

windowdecoration2

**Comment by Acer54** [comment]
I was talking about the "loading animation" (a rolling, gray cyrcle over the window) which would appear if you add a few titles from the meda-player using the included search-engine for youtube (online-results active)... I do not mean the "loading" screen at startup of the script.... ;-)

**Comment by HiranChaudhuri** [comment]
Ah that one. I have seen it once. Since then I was probably just adding small amounts or my setup is just fast enough.
Once however I was able to move the whole window - just as I demonstrated above. I think it was since no search results were found and a dialog box popped up. This dialog box had window controls that I used to minimize the application - and behind it there was a huge loading.gif on my desktop.

**Comment by Acer54** [comment]
Correct, this was the reason, why I have included this argument (--fullscreen) but do not use it. Because it is essential for the user, that he is getting the information if something is "loading" at the moment, otherwise he might think, that the programm is frozen.
I'll try to add a fixed amount of pixels, which is added to the system-reported one... Nearly all reports from users (with raspbian) are telling me the same, there are always 3-4 pixel rows missing where the window-decoration is visible instead.

Will have a look into this during next week. I will have a look at the reportet stylesheet topic as well...
Thanks for your help!

**Comment by HiranChaudhuri** [comment]
That's why I created this PR. It just adds the command line switch to the systemd startup of webradio, and at least that issue should be resolved.

I am still impressed by the quality of your code including documentation, and fully agree to keep the user informed about ongoing activity. :-)

**Pull request closed without merging**
